Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,21 +45,21 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           slug: JonathanDannessa/SE390-Mini-capstone-project
 
-      - name: Setup EAS
-        uses: expo/expo-github-action@v8
-        with:
-          eas-version: latest
-          token: ${{ secrets.EXPO_TOKEN }}
+      # - name: Setup EAS
+      #   uses: expo/expo-github-action@v8
+      #   with:
+      #     eas-version: latest
+      #     token: ${{ secrets.EXPO_TOKEN }}
 
       
-      - name: Build with EAS
-        run: |
-          cd Concordia_Campus_App
-          npm install eas-cli
-          npx eas build --platform ios --non-interactive --profile build-and-maestro-test
-          if [ $? -ne 0 ]; then
-            echo "EAS build failed!"
-            exit 1
-          fi
+      # - name: Build with EAS
+      #   run: |
+      #     cd Concordia_Campus_App
+      #     npm install eas-cli
+      #     npx eas build --platform ios --non-interactive --profile build-and-maestro-test
+      #     if [ $? -ne 0 ]; then
+      #       echo "EAS build failed!"
+      #       exit 1
+      #     fi
 
 
